MARKET-Online-programacion4/Models/Pedido.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MARKET_Online_programacion4.Models
{
    public class Pedido
    {
        [Key]
        public int Id { get; set; }

        
        public DateTime FechaCreacion { get; set; }

        public int Clienteid { get; set; }

        [ForeignKey("Clienteid")]
        public Cliente Cliente { get; set; }

        public ICollection<Detalle> Detalles  { get; set; }

    }
}

MARKET-Online-programacion4/Controllers/PedidoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MARKET_Online_programacion4.DataBase;
using MARKET_Online_programacion4.Models;
using MARKET_Online_programacion4.ViewsModel;

namespace MARKET_Online_programacion4.Controllers
{
    public class PedidoController : Controller
    {
        private MarketContext db = new MarketContext();

        // GET: Pedido
        public ActionResult Index()
        {
            var pedidos = db.Pedidos.Include(p => p.Cliente);
            return View(pedidos.ToList());
        }

        // GET: Pedido/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = db.Pedidos.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            return View(pedido);
        }

        // GET: Pedido/Create
        public ActionResult Create()
        {
            var clientes = db.Clientes.ToList();
            var pedidoView = new PedidoFormViewModel
            {
                Pedido = new Pedido(),
                Clientes = clientes,
                Producto = new List<DetalleFormViewModel>()
            };
            Session["pedidoView"] = pedidoView;
            return View("PedidoForm", pedidoView);

            //ViewBag.Clienteid = new SelectList(db.Clientes, "Id", "Nombre");

        }

        [HttpGet]
        public ActionResult Agregar()
        {
            var productos = db.Productos.ToList();
            var viewProductoOrden = new DetalleFormViewModel
            {
              
                Productos= productos,

            };

            return View("Agregar", viewProductoOrden);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Agregar(DetalleFormViewModel viewProductoOrden)
        {
            var pedidoView = Session["pedidoView"] as PedidoFormViewModel;
            var cantidad = viewProductoOrden.Detalle.Cantidad;
            var ProductoInDb = db.Productos.Find(viewProductoOrden.Detalle.Productoid);
            var detalle = new Detalle
            {
                Productoid = ProductoInDb.Id,
                PrecioM = ProductoInDb.Precio,
                Cantidad = cantidad, 
                Descuento= 0,
                Total= ProductoInDb.Precio * cantidad,
                Producto= ProductoInDb


            };

            viewProductoOrden = new DetalleFormViewModel
            {
                Detalle = detalle,
            };

            pedidoView.Producto.Add(viewProductoOrden);
            return View("PedidoForm", pedidoView);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Guardar(PedidoFormViewModel pedidoView)
        {
            pedidoView.Producto = (Session["pedidoView"] as PedidoFormViewModel).Producto;
            Pedido pedido = pedidoView.Pedido;

            db.Pedidos.Add(pedido);
            db.SaveChanges();

            var PedidoId = db.Pedidos.ToList().Select(p => p.Id).Max();

            foreach (var producto in pedidoView.Producto)
            {
                var detalle = new Detalle
                {
                    Pedidoid = PedidoId,
                    Productoid = producto.Detalle.Producto.Id,
                    PrecioM = producto.Detalle.Producto.Precio,
                    Cantidad = producto.Detalle.Cantidad,
                    Total = producto.Detalle.Total,
                    Descuento = producto.Detalle.Descuento,
                };

                db.Detalles.Add(detalle);
                db.SaveChanges();
            }

            var cliente = db.Clientes.ToList();
            var pedidoViewNuevo = new PedidoFormViewModel
            {
                Pedido = new Pedido(),
                Clientes = cliente,
                Producto = new List<DetalleFormViewModel>()
            };

            Session["pedidoView"] = pedidoViewNuevo;
            return View("PedidoForm", pedidoViewNuevo);

        }

        


            // POST: Pedido/Create
            // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
            // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,FechaCreacion,Clienteid")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                db.Pedidos.Add(pedido);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Clienteid = new SelectList(db.Clientes, "Id", "Nombre", pedido.Clienteid);
            return View(pedido);
        }

        // GET: Pedido/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = db.Pedidos.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            ViewBag.Clienteid = new SelectList(db.Clientes, "Id", "Nombre", pedido.Clienteid);
            return View(pedido);
        }

        // POST: Pedido/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,FechaCreacion,Clienteid")] Pedido pedido)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pedido).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.Clienteid = new SelectList(db.Clientes, "Id", "Nombre", pedido.Clienteid);
            return View(pedido);
        }

        // GET: Pedido/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pedido pedido = db.Pedidos.Find(id);
            if (pedido == null)
            {
                return HttpNotFound();
            }
            return View(pedido);
        }

        // POST: Pedido/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pedido pedido = db.Pedidos.Find(id);
            db.Pedidos.Remove(pedido);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MARKET-Online-programacion4/Views/Pedido/Agregar.cshtml
@model MARKET_Online_programacion4.ViewsModel.DetalleFormViewModel
@{
    ViewBag.Title = "Agregar";
}

<h2>Agregar</h2>

@using (Html.BeginForm("Agregar", "Pedido"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Pedido</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Detalle.Productoid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Detalle.Productoid, new SelectList(Model.Productos, "Id", "Nombre"), "Seleccione un producto", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Detalle.Productoid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Detalle.Cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Detalle.Cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Detalle.Cantidad, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.Detalle.Id)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Agregar" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

MARKET-Online-programacion4/Views/Pedido/Create.cshtml
@model MARKET_Online_programacion4.Models.Pedido

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pedido</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FechaCreacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaCreacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaCreacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Clienteid, "Clienteid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Clienteid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Clienteid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MARKET-Online-programacion4/Views/Pedido/Delete.cshtml
@model MARKET_Online_programacion4.Models.Pedido

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MARKET-Online-programacion4/Views/Pedido/Details.cshtml
@model MARKET_Online_programacion4.Models.Pedido

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Pedido</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cliente.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cliente.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

MARKET-Online-programacion4/Views/Pedido/Edit.cshtml
@model MARKET_Online_programacion4.Models.Pedido

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pedido</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.FechaCreacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaCreacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaCreacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Clienteid, "Clienteid", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Clienteid", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Clienteid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

MARKET-Online-programacion4/Views/Pedido/Index.cshtml
@model IEnumerable<MARKET_Online_programacion4.Models.Pedido>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Cliente.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Cliente.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaCreacion)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MARKET-Online-programacion4/Views/Pedido/PedidoForm.cshtml
@model MARKET_Online_programacion4.ViewsModel.PedidoFormViewModel
@{
    ViewBag.Title = "PedidoForm";
}

<h2>PedidoForm</h2>

@using (Html.BeginForm("Guardar", "Pedido"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Pedido</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Pedido.Clienteid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Pedido.Clienteid, new SelectList(Model.Clientes, "Id", "Nombre"), "Seleccione un cliente", new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Pedido.Clienteid, "{0:MM/dd//yyyy}", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Pedido.FechaCreacion , htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Pedido.FechaCreacion, new { htmlAttributes = new { @class = "form-control btn-btn-Primary" } })
                @Html.ValidationMessageFor(model => model.Pedido.FechaCreacion, "", new { @class = "text-danger" })
            </div>
        </div>
        @Html.HiddenFor(model => model.Pedido.Id)

        <div class="form-group">
            @Html.ActionLink("Agregar un producto", "Agregar", new { }, new { @class = "btn-btn-Success" })
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>

    <table class="table-bordered table-hover">
        <thead>
            <tr>
                <td>
                    @Html.DisplayNameFor(model => model.Tabla.Detalle.Producto.Nombre)
                    @Html.DisplayNameFor(model => model.Tabla.Detalle.Producto.Precio)
                    @Html.DisplayNameFor(model => model.Tabla.Detalle.Cantidad)
                    @Html.DisplayNameFor(model => model.Tabla.Detalle.Total)
                </td>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.Producto.Count(); i++)
            {
               <tr>
                <td>@Html.DisplayFor(m => Model.Producto[i].Detalle.Producto.Nombre)</td>
                <td>@Html.DisplayFor(m => Model.Producto[i].Detalle.Producto.Precio)</td>
                <td>@Html.DisplayFor(m => Model.Producto[i].Detalle.Cantidad)</td>
                <td>@Html.DisplayFor(m => Model.Producto[i].Detalle.Total)</td>
                <td>
                    @Html.ActionLink("Eliminar","Delete", new {id = Model.Producto[i].Detalle.Id }, new {@class ="btn-btn-danger" } )
                </td>
                </tr>

              }
        </tbody>
    </table>



}

<div>
    @Html.ActionLink("Volver a la lista", "Index")
</div>