MARKET-Online-programacion4/Models/Producto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace MARKET_Online_programacion4.Models
{
    public class Producto
    {
        public int Id { get; set; }

        [Index(IsUnique = true)]
        [StringLength(15)]

        public string Codigo { get; set; }
        [Required]
        [StringLength(75)]

        public string Nombre { get; set; }
        [Required]

        public bool Estado { get; set; }
        [Required]

        public DateTime FechaCreacion { get; set; }

        public int UnidadMedidaId { get; set; }

        public int ClasificacionProductoId { get; set; }

        public double Precio { get; set; } // era int y lo puse double

        [ForeignKey("UnidadMedidaId")]
        public UnidadMedida UnidadMedida { get; set; }

        [ForeignKey("ClasificacionProductoId")]
        public ClasificacionProducto ClasificacionProducto { get; set; }


    }
}

MARKET-Online-programacion4/Controllers/ProductoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MARKET_Online_programacion4.DataBase;
using MARKET_Online_programacion4.Models;
using MARKET_Online_programacion4.ViewsModel;

namespace MARKET_Online_programacion4.Controllers
{
    public class ProductoController : Controller
    {
        private MarketContext db = new MarketContext();

        // GET: Producto
        public ActionResult Index()
        {
            var productos = db.Productos.Include(p => p.ClasificacionProducto).Include(p => p.UnidadMedida);
            return View(productos.ToList());
        }

        // GET: Producto/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productos.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // GET: Producto/Create
        public ActionResult Create()
        {
            var producto = new Producto();
            var unidadmedidas = db.UnidadMedidas.ToList();
            var clasificacionproducto = db.ClasificacionProductos.ToList();
            var ViewModel = new ProductoFormViewModel
            {
                Producto = producto,
                UnidadMedidas= unidadmedidas ,
                ClasificacionProductos=  clasificacionproducto
            };
            ViewBag.ClasificacionProductoId = new SelectList(db.ClasificacionProductos, "Id", "Codigo");
            ViewBag.UnidadMedidaId = new SelectList(db.UnidadMedidas, "Id", "Codigo");

            return View("ProductoForm", ViewModel);
            
            
        }

        // POST: Producto/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "Id,Codigo,Nombre,Estado,FechaCreacion,UnidadMedidaId,ClasificacionProductoId,Precio")] Producto producto)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Productos.Add(producto);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    ViewBag.ClasificacionProductoId = new SelectList(db.ClasificacionProductos, "Id", "Codigo", producto.ClasificacionProductoId);
        //    ViewBag.UnidadMedidaId = new SelectList(db.UnidadMedidas, "Id", "Codigo", producto.UnidadMedidaId);
        //    return View(producto);
        //}

        // GET: Producto/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productos.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            var unidadmedidas = db.UnidadMedidas.ToList();
            var clasificacionproducto = db.ClasificacionProductos.ToList();
            var ViewModel = new ProductoFormViewModel
            {
                Producto = producto,
                UnidadMedidas = unidadmedidas, 
                ClasificacionProductos= clasificacionproducto
            };

            ViewBag.ClasificacionProductoId = new SelectList(db.ClasificacionProductos, "Id", "Codigo", producto.ClasificacionProductoId);
            ViewBag.UnidadMedidaId = new SelectList(db.UnidadMedidas, "Id", "Codigo", producto.UnidadMedidaId);

            return View("ProductoForm", ViewModel);

        }

        // POST: Producto/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "Id,Codigo,Nombre,Estado,FechaCreacion,UnidadMedidaId,ClasificacionProductoId,Precio")] Producto producto)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Entry(producto).State = EntityState.Modified;
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }
        //    ViewBag.ClasificacionProductoId = new SelectList(db.ClasificacionProductos, "Id", "Codigo", producto.ClasificacionProductoId);
        //    ViewBag.UnidadMedidaId = new SelectList(db.UnidadMedidas, "Id", "Codigo", producto.UnidadMedidaId);
        //    return View(producto);
        //}

        // GET: Producto/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Producto producto = db.Productos.Find(id);
            if (producto == null)
            {
                return HttpNotFound();
            }
            return View(producto);
        }

        // POST: Producto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Producto producto = db.Productos.Find(id);
            db.Productos.Remove(producto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Guardar( Producto producto)
        {
           
            if (ModelState.IsValid)
            {
                if (producto.Id == 0)
                {
                    db.Productos.Add(producto);
                }
                else
                {
                    db.Entry(producto).State = EntityState.Modified;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            //ViewBag.ClasificacionProductoId = new SelectList(db.ClasificacionProductos, "Id", "Codigo", producto.ClasificacionProductoId);
            //ViewBag.UnidadMedidaId = new SelectList(db.UnidadMedidas, "Id", "Codigo", producto.UnidadMedidaId);
            return View(producto);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

MARKET-Online-programacion4/Views/Producto/Create.cshtml
@model MARKET_Online_programacion4.Models.Producto

@{
    ViewBag.Title = "Crear un nuevo producto para la tienda";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaCreacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaCreacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaCreacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnidadMedidaId, "UnidadMedidaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UnidadMedidaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UnidadMedidaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClasificacionProductoId, "ClasificacionProductoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClasificacionProductoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClasificacionProductoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Volver a la pantalla principal", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MARKET-Online-programacion4/Views/Producto/Delete.cshtml
@model MARKET_Online_programacion4.Models.Producto

@{
    ViewBag.Title = "Borrar producto";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClasificacionProducto.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClasificacionProducto.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnidadMedida.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnidadMedida.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

MARKET-Online-programacion4/Views/Producto/Details.cshtml
@model MARKET_Online_programacion4.Models.Producto

@{
    ViewBag.Title = "Detalles";
}

<h2>Details</h2>

<div>
    <h4>Producto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ClasificacionProducto.Clasificacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ClasificacionProducto.Clasificacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UnidadMedida.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UnidadMedida.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Codigo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Codigo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Estado)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Estado)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaCreacion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Precio)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Precio)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Volver al inicio", "Index")
</p>

MARKET-Online-programacion4/Views/Producto/Edit.cshtml
@model MARKET_Online_programacion4.Models.Producto

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Producto</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Estado)
                    @Html.ValidationMessageFor(model => model.Estado, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaCreacion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaCreacion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaCreacion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnidadMedidaId, "UnidadMedidaId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UnidadMedidaId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UnidadMedidaId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ClasificacionProductoId, "ClasificacionProductoId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ClasificacionProductoId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ClasificacionProductoId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Precio, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Precio, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MARKET-Online-programacion4/Views/Producto/Index.cshtml
@model IEnumerable<MARKET_Online_programacion4.Models.Producto>

@{
    ViewBag.Title = "Inicio";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Crear un nuevo producto", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ClasificacionProducto.Clasificacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UnidadMedida.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Estado)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaCreacion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Precio)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ClasificacionProducto.Clasificacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.UnidadMedida.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Codigo)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Estado)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.FechaCreacion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Precio)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

MARKET-Online-programacion4/Views/Producto/ProductoForm.cshtml
@model MARKET_Online_programacion4.ViewsModel.ProductoFormViewModel
@{
    ViewBag.Title = "ProductoForm";
}

<h2>Mantenimiento de los productos</h2>


@using (Html.BeginForm("Guardar", "Producto",null,FormMethod.Post, new {enctype= "multipart/form-data"} ))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Producto</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Producto.Id)


    <div class="form-group">
        @Html.LabelFor(model => model.Producto.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Producto.Codigo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Producto.Codigo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Producto.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Producto.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Producto.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Producto.Estado, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Producto.Estado)
                @Html.ValidationMessageFor(model => model.Producto.Estado, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Producto.FechaCreacion, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Producto.FechaCreacion, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Producto.FechaCreacion, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Producto.UnidadMedidaId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UnidadMedidaId", null, "Selecciona una medida oficial", new { htmlAttributes = new { @class = "form-control" } })
           @*@Html.DropDownList("UnidadMedidaId", null, htmlAttributes: new { @class = "form-control" })*@
            @Html.ValidationMessageFor(model => model.Producto.UnidadMedidaId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Producto.ClasificacionProductoId , htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ClasificacionProductoId", null, "Selecciona un clasificacion valida", new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Producto.ClasificacionProductoId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Producto.Precio, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Producto.Precio, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Producto.Precio, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Guardar" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Volver a la pantalla principal", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}